import { resolve } from 'node:path';
import { test, expect } from '@playwright/test';

test('owner adds a shop, merchant changes password, adds a flower and processes its order', async ({ page, request }) => {
  test.setTimeout(60000);
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/admin');
  await page.getByLabel('Login', { exact: true }).fill('e2e-admin');
  await page.getByLabel('Parol', { exact: true }).fill('Temporary-Test-Password');
  await page.getByRole('button', { name: 'Kirish', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'O‘zingizga yangi parol qo‘ying' })).toBeVisible();
  await page.getByLabel('Yangi parol', { exact: true }).fill('Owner-Personal-Password');
  await page.getByLabel('Yangi parolni takrorlang', { exact: true }).fill('Owner-Personal-Password');
  await page.getByRole('button', { name: 'Yangi parolni saqlash' }).click();
  await page.getByRole('button', { name: 'Yangi do‘kon', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Do‘kon nomi', { exact: true }).fill('Panel Test Flowers');
  await dialog.getByLabel('Qisqa tavsif', { exact: true }).fill('Demo test do‘koni');
  await dialog.getByLabel('Manzil', { exact: true }).fill('Urganch, demo sinov ko‘chasi');
  await dialog.getByLabel('Do‘kon telefoni', { exact: true }).fill('+998900000000');
  await dialog.getByLabel('Do‘kon egasining Telegram ID’si', { exact: true }).fill('123456789');
  await dialog.getByLabel('Do‘kon logini', { exact: true }).fill('panel.test');
  await dialog.getByLabel('Vaqtinchalik parol', { exact: true }).fill('Merchant-Temporary-Password');
  await dialog.getByRole('checkbox', { name: 'Do‘konni katalogda ochish' }).check();
  await dialog.getByRole('button', { name: 'Do‘konni saqlash' }).click();
  await expect(page.getByRole('heading', { name: 'Do‘kon egasiga beriladigan ma’lumotlar' })).toBeVisible();
  await page.getByRole('button', { name: 'Ma’lumotlarni oldim' }).click();
  await expect(page.locator('.admin-shop-list')).toContainText('Panel Test Flowers');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/gulbar-admin-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/gulbar-admin-desktop.png', fullPage: true });
  await page.goto('/merchant');
  await page.getByRole('button', { name: 'Login va parol bilan kirish' }).click();
  await page.getByLabel('Login', { exact: true }).fill('panel.test');
  await page.getByLabel('Parol', { exact: true }).fill('Merchant-Temporary-Password');
  await page.getByRole('button', { name: 'Kirish', exact: true }).click();
  await page.getByLabel('Yangi parol', { exact: true }).fill('Merchant-Personal-Password');
  await page.getByLabel('Yangi parolni takrorlang', { exact: true }).fill('Merchant-Personal-Password');
  await page.getByRole('button', { name: 'Yangi parolni saqlash' }).click();
  await expect(page.locator('.page-heading')).toContainText('Panel Test Flowers');
  await page.getByRole('button', { name: 'Gullar va narxlar', exact: true }).click();
  await page.getByRole('button', { name: 'Gul qo‘shish', exact: true }).click();
  await dialog.getByLabel('Nomi', { exact: true }).fill('Panel test guldastasi');
  await dialog.getByLabel('Tavsifi', { exact: true }).fill('Sinov guldastasi');
  await dialog.getByLabel('Narxi (so‘m)', { exact: true }).fill('150000');
  await dialog.getByLabel('Mavjud soni', { exact: true }).fill('5');
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.getByLabel('Telefondan rasm tanlash', { exact: true }).setInputFiles(resolve('public/images/pink-bouquet.jpg'));
  await expect(dialog.getByAltText('Tanlangan gul rasmi')).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Saqlash', exact: true })).toBeEnabled();
  await page.screenshot({ path: 'test-results/gulbar-gallery-mobile.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Saqlash', exact: true }).click();
  await expect(page.locator('.merchant-products')).toContainText('Panel test guldastasi');
  const catalog = await (await request.get('/api/catalog')).json();
  const shop = catalog.shops.find((s: any) => s.name === 'Panel Test Flowers');
  const product = catalog.products.find((p: any) => p.shopId === shop.id);
  expect(product.image).toMatch(/^\/api\/images\//);
  const photo = await request.get(product.image);
  expect(photo.status()).toBe(200);
  expect(photo.headers()['content-type']).toContain('image/jpeg');
  const order = await request.post('/api/orders', { headers: { 'X-Demo-User': 'panel-test-customer-12345' }, data: { requestKey: crypto.randomUUID(), shopId: shop.id, items: [{ productId: product.id, quantity: 1 }], customer: { name: 'Panel test', phone: '+998900000000', recipient: 'Demo recipient', recipientPhone: '+998900000000', address: 'Urganch, demo test', deliveryTime: 'soon', anonymous: false, note: 'Demo, no delivery' } } });
  expect(order.status()).toBe(201);
  await page.getByRole('button', { name: /Buyurtmalar \(/ }).click();
  await page.getByRole('button', { name: 'Yangilash', exact: true }).click();
  await expect(page.locator('.order-card')).toContainText('Panel test guldastasi');
  await page.getByRole('button', { name: 'Qabul qilindi', exact: true }).click();
  await page.getByRole('button', { name: 'Yo‘lda', exact: true }).click();
  await page.getByRole('button', { name: 'Yetkazildi', exact: true }).click();
  await expect(page.locator('.order-card .status')).toContainText('Yetkazildi');
  await page.getByRole('button', { name: 'Chiqish', exact: true }).click();
  await page.getByLabel('Login', { exact: true }).fill('panel.test');
  await page.getByLabel('Parol', { exact: true }).fill('Merchant-Temporary-Password');
  await page.getByRole('button', { name: 'Kirish', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Login yoki parol noto‘g‘ri');
  const owner = await (await request.post('/api/auth/login', { data: { login: 'e2e-admin', password: 'Owner-Personal-Password' } })).json();
  const closed = await request.patch(`/api/admin/shops/${shop.id}/settings`, { headers: { Authorization: `Bearer ${owner.token}` }, data: { shop: { ...shop, active: false }, phone: '+998900000000', telegramChatId: '123456789' } });
  expect(closed.status()).toBe(200);
  // the owner deletes the test shop from the panel: the button stays off until the name is typed
  await page.goto('/admin');
  await page.getByLabel('Login', { exact: true }).fill('e2e-admin');
  await page.getByLabel('Parol', { exact: true }).fill('Owner-Personal-Password');
  await page.getByRole('button', { name: 'Kirish', exact: true }).click();
  const card = page.locator('.adm-shop', { hasText: 'Panel Test Flowers' });
  await card.getByRole('button', { name: /O‘chirish/ }).click();
  const confirm = page.getByRole('dialog', { name: 'Do‘konni o‘chirish' });
  await expect(confirm.getByRole('button', { name: 'Do‘konni o‘chirish' })).toBeDisabled();
  await confirm.getByLabel('Do‘kon nomi', { exact: true }).fill('Panel Test');
  await expect(confirm.getByRole('button', { name: 'Do‘konni o‘chirish' })).toBeDisabled();
  await confirm.getByLabel('Do‘kon nomi', { exact: true }).fill('Panel Test Flowers');
  await confirm.getByRole('button', { name: 'Do‘konni o‘chirish' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'o‘chirildi' })).toBeVisible();
  await expect(page.locator('.admin-shop-list')).not.toContainText('Panel Test Flowers');
  const after = await (await request.get('/api/catalog')).json();
  expect(after.shops.some((x: any) => x.id === shop.id)).toBe(false);
  expect((await request.post('/api/auth/login', { data: { login: 'panel.test', password: 'Merchant-Personal-Password' } })).status()).toBe(401);
  expect(errors).toEqual([]);
});
