const files = { 'photo-1563241527-3004b7be0ffd': 'pink-bouquet', 'photo-1525310072745-f49212b5ac6d': 'lily', 'photo-1518895949257-7621c3c786d7': 'rose', 'photo-1457089328109-e5d9bd499191': 'gift', 'photo-1561181286-d3fee7d55364': 'spring', 'photo-1490750967868-88aa4486c946': 'sunshine' };
const photo = id => `/images/${files[id]}.jpg`;
const demoShops = [
  { id: 'lola', name: 'Lola Flowers', subtitle: 'Nafis guldastalar va mehr', address: 'Urganch markazi · namunaviy manzil', deliveryFee: 20000, deliveryTime: '60–90 daqiqa', color: '#f3dce2', initials: 'LF', active: true },
  { id: 'bloom', name: 'Bloom Studio', subtitle: 'Har lahzaga o‘ziga xos gul', address: 'Urganch · namunaviy manzil', deliveryFee: 25000, deliveryTime: '60–120 daqiqa', color: '#e2e9dd', initials: 'BS', active: true },
  { id: 'rayhon', name: 'Rayhon', subtitle: 'Gullar bilan aytilgan so‘zlar', address: 'Urganch · namunaviy manzil', deliveryFee: 15000, deliveryTime: '60–90 daqiqa', color: '#f0e4d4', initials: 'R', active: true },
];
const demoProducts = [
  { id: 'p1', shopId: 'lola', name: 'Pushti kayfiyat', description: 'Pushti atirgullar va mavsumiy gullardan nafis guldasta. Gul tarkibi do‘kon bilan tasdiqlanadi.', price: 280000, category: 'bouquet', image: photo('photo-1563241527-3004b7be0ffd'), stock: 8, audience: ['ona', 'rafiqa', 'qiz'], badge: 'Guldasta' },
  { id: 'p2', shopId: 'bloom', name: 'Oq orzu', description: 'Oq gullar, yashil barglar va tabiiy o‘ram. Sokin, nafis sovg‘a.', price: 320000, category: 'bouquet', image: photo('photo-1525310072745-f49212b5ac6d'), stock: 5, audience: ['ona', 'hamkasb'], badge: 'Nafis tanlov' },
  { id: 'p3', shopId: 'lola', name: 'Sevgi atirgullari', description: 'Qizil atirgullardan klassik guldasta. Sovg‘a kartochkasi qo‘shish mumkin.', price: 350000, category: 'rose', image: photo('photo-1518895949257-7621c3c786d7'), stock: 7, audience: ['rafiqa'], badge: 'Atirgullar' },
  { id: 'p4', shopId: 'rayhon', name: 'Bahor nafasi', description: 'Rang-barang mavsumiy gullar. Yorqin kun uchun yorqin sovg‘a.', price: 240000, category: 'tulip', image: photo('photo-1457089328109-e5d9bd499191'), stock: 6, audience: ['qiz', 'dost', 'hamkasb'], badge: 'Mavsumiy' },
  { id: 'p5', shopId: 'bloom', name: 'Kichik quvonch', description: 'Ixcham kompozitsiya, nafis o‘ram va samimiy tilaklar.', price: 190000, category: 'box', image: photo('photo-1561181286-d3fee7d55364'), stock: 4, audience: ['dost', 'hamkasb', 'qiz'], badge: 'Gul qutisi' },
  { id: 'p6', shopId: 'rayhon', name: 'Quyoshli kun', description: 'Iliq rangdagi gullardan mavsumiy kompozitsiya. Aniq tarkib do‘kon bilan kelishiladi.', price: 260000, category: 'bouquet', image: photo('photo-1490750967868-88aa4486c946'), stock: 9, audience: ['ona', 'dost', 'qiz'], badge: 'Guldasta' },
];

const madinaShop = { id: 'madina', name: 'Madina Gullari', subtitle: 'Gullar va sovg‘alar · Urganch, Xiva', address: 'Urganch · Xorazm bo‘ylab 6 ta filial', deliveryFee: 25000, deliveryTime: '60–120 daqiqa', color: '#efe3c8', initials: 'MG', active: true, logo: '/images/logo-madina.webp' };
// Madina Gullari photos are the shop's own; names and prices are placeholders until the shop confirms them.
const madinaProducts = [
  { id: 'm1', shopId: 'madina', name: 'Oq Bulut', description: 'Oq atirgullardan juda katta guldasta: to‘q yashil lenta va yurak shaklidagi QR belgi bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 3000000, category: 'rose', image: '/images/madina-oq-bulut.webp', stock: 3, audience: ['rafiqa', 'ona'], badge: 'Atirgullar' },
  { id: 'm2', shopId: 'madina', name: 'Pushti Tuman', description: 'Yumshoq pushti buta atirgullardan katta guldasta, krem rangli lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 3500000, category: 'rose', image: '/images/madina-pushti-tuman.webp', stock: 2, audience: ['qiz', 'rafiqa'], badge: 'Atirgullar' },
  { id: 'm3', shopId: 'madina', name: 'Anor Rang', description: 'To‘q pushti buta atirgullar va evkalipt, bordo rangli lentalar bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 2900000, category: 'rose', image: '/images/madina-anor-rang.webp', stock: 3, audience: ['rafiqa', 'qiz'], badge: 'Atirgullar' },
  { id: 'm4', shopId: 'madina', name: 'Osmon va Qor', description: 'Ko‘k gortenziya va oppoq xrizantemalardan to‘p-to‘q guldasta. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1900000, category: 'bouquet', image: '/images/madina-osmon-va-qor.webp', stock: 4, audience: ['ona', 'hamkasb'], badge: 'Gortenziya' },
  { id: 'm5', shopId: 'madina', name: 'Quyosh Nuri', description: 'Sariq xrizantema, oq gortenziya, lilya va qizil giperikum rezavorlari. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1450000, category: 'bouquet', image: '/images/madina-quyosh-nuri.webp', stock: 5, audience: ['dost', 'ona', 'hamkasb'], badge: 'Mavsumiy' },
  { id: 'm6', shopId: 'madina', name: 'Firuza Qirov', description: 'Oq gortenziya, atirgul va xrizantema, firuza rangli o‘ram va yurakli belgi bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1350000, category: 'bouquet', image: '/images/madina-firuza-qirov.webp', stock: 5, audience: ['ona', 'hamkasb'], badge: 'Gortenziya' },
  { id: 'm7', shopId: 'madina', name: 'Moviy Orzu', description: 'Och ko‘k gortenziya va oq atirgullar, kulrang o‘ram va ochiq ko‘k lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1650000, category: 'bouquet', image: '/images/madina-moviy-orzu.webp', stock: 4, audience: ['qiz', 'ona'], badge: 'Gortenziya' },
  { id: 'm8', shopId: 'madina', name: 'Marvarid', description: 'Oq gortenziya, atirgul va yashil giperikum, marvarid hoshiyali nafis o‘ramda. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1750000, category: 'bouquet', image: '/images/madina-marvarid.webp', stock: 3, audience: ['rafiqa', 'hamkasb'], badge: 'Nafis tanlov' },
  { id: 'm9', shopId: 'madina', name: 'Oppoq Kayfiyat', description: 'Oq xrizantema, atirgul va lilya kurtaklari, oq o‘ram va kumush lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 950000, category: 'bouquet', image: '/images/madina-oppoq-kayfiyat.webp', stock: 6, audience: ['ona', 'hamkasb', 'dost'], badge: 'Mavsumiy' },
  { id: 'm10', shopId: 'madina', name: 'Pastel Tong', description: 'Pushti atirgullar, ko‘k va siyohrang gortenziya, chinnigullar va evkalipt. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1600000, category: 'bouquet', image: '/images/madina-pastel-tong.webp', stock: 4, audience: ['qiz', 'dost'], badge: 'Gortenziya' },
  { id: 'm11', shopId: 'madina', name: 'Pushti Lilya', description: 'Pushti lilya, oq xrizantema va siyohrang matiola, to‘rli marvarid o‘ramda. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1150000, category: 'bouquet', image: '/images/madina-pushti-lilya.webp', stock: 5, audience: ['qiz', 'rafiqa', 'dost'], badge: 'Mavsumiy' },
  { id: 'm12', shopId: 'madina', name: 'Zaytun Bog‘i', description: 'Oq lilya, gortenziya, atirgul va yashil giperikum, zaytun rangli o‘ramda. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1400000, category: 'bouquet', image: '/images/madina-zaytun-bogi.webp', stock: 4, audience: ['ona', 'hamkasb'], badge: 'Mavsumiy' },
  { id: 'm13', shopId: 'madina', name: 'Shaftoli Tongi', description: 'Ikki rangli pushti atirgul, sariq buta atirgul va oq gortenziya. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1800000, category: 'bouquet', image: '/images/madina-shaftoli-tongi.webp', stock: 3, audience: ['qiz', 'dost', 'rafiqa'], badge: 'Nafis tanlov' },
  { id: 'm14', shopId: 'madina', name: 'Xorazm Osmoni', description: 'To‘q ko‘k gortenziya, oq romashka va xrizantema, shaftoli rangli buta atirgullar. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1550000, category: 'bouquet', image: '/images/madina-xorazm-osmoni.webp', stock: 4, audience: ['ona', 'dost', 'hamkasb'], badge: 'Gortenziya' },
];
const goldShop = { id: 'goldflowers', name: 'Gold Flowers', subtitle: 'Gullar va sovg‘alar · 9:00–01:00', address: 'Pahlavon Mahmud 38 (Amir.T Park), Urganch', deliveryFee: 20000, deliveryTime: '60–90 daqiqa', color: '#ecdcae', initials: 'GF', active: true, hours: { open: '09:00', close: '01:00' }, logo: '/images/logo-goldflowers.webp' };
// Gold Flowers photos are the shop's own; names and prices are placeholders until the shop confirms them.
const goldProducts = [
  { id: 'g1', shopId: 'goldflowers', name: 'Pushti Shom', description: 'Yorqin pushti atirgullardan guldasta, qaymoq rangli o‘ram va pushti lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 950000, category: 'rose', image: '/images/goldflowers-pushti-shom.webp', stock: 5, audience: ['rafiqa', 'qiz', 'ona'], badge: 'Atirgullar' },
  { id: 'g2', shopId: 'goldflowers', name: 'Qishki Qizil', description: 'Qizil atirgullar va yashil barglar, kulrang o‘ram hamda oltin yozuvli qora lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 650000, category: 'rose', image: '/images/goldflowers-qishki-qizil.webp', stock: 6, audience: ['rafiqa'], badge: 'Atirgullar' },
  { id: 'g3', shopId: 'goldflowers', name: 'Marjon', description: 'Pushti hoshiyali atirgullar va alstromeriya, evkalipt, marjon rangli o‘ramda. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 900000, category: 'bouquet', image: '/images/goldflowers-marjon.webp', stock: 4, audience: ['ona', 'qiz', 'hamkasb'], badge: 'Mavsumiy' },
  { id: 'g4', shopId: 'goldflowers', name: 'Limon Kayfiyat', description: 'Sariq buta atirgullar, oq alstromeriya va gipsofila, yalpiz rangli o‘ramda. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 850000, category: 'bouquet', image: '/images/goldflowers-limon-kayfiyat.webp', stock: 4, audience: ['dost', 'hamkasb', 'qiz'], badge: 'Mavsumiy' },
  { id: 'g5', shopId: 'goldflowers', name: 'Firuza Qutisi', description: 'Qizil atirgullar, ko‘k alstromeriya va gipsofila, firuza rangli dumaloq qutida. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 750000, category: 'box', image: '/images/goldflowers-firuza-qutisi.webp', stock: 5, audience: ['rafiqa', 'dost'], badge: 'Gul qutisi' },
];
const sonyaShop = { id: 'sonya', name: 'So‘nya Gullari', subtitle: 'Savat, buket va gullar · 8:30–00:00', address: 'Amir Temur istirohat bog‘i, Urganch', deliveryFee: 20000, deliveryTime: '60–90 daqiqa', color: '#e9ddd0', initials: 'SG', active: true, hours: { open: '08:30', close: '00:00' }, logo: '/images/logo-sonya.webp' };
// So'nya Gullari photos are the shop's own; names and prices are placeholders until the shop confirms them.
const sonyaProducts = [
  { id: 's1', shopId: 'sonya', name: 'Shabnam', description: 'Shaftoli va oq buta atirgullardan katta guldasta, oq o‘ram va kumush lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 2400000, category: 'rose', image: '/images/sonya-shabnam.webp', stock: 3, audience: ['rafiqa', 'qiz', 'ona'], badge: 'Atirgullar' },
  { id: 's2', shopId: 'sonya', name: 'Sariq Savat', description: 'Sariq atirgullar va gipsofila, to‘qilgan savatda, yalpiz rangli lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1300000, category: 'rose', image: '/images/sonya-sariq-savat.webp', stock: 4, audience: ['ona', 'dost', 'hamkasb'], badge: 'Savat' },
  { id: 's3', shopId: 'sonya', name: 'Malina Savati', description: 'Yorqin pushti buta atirgullar, tabiiy savatda, qizil lenta bilan. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 1100000, category: 'rose', image: '/images/sonya-malina-savati.webp', stock: 4, audience: ['qiz', 'dost', 'hamkasb'], badge: 'Savat' },
  { id: 's4', shopId: 'sonya', name: 'Shom Shafaqi', description: 'Pushti va oq buta atirgullardan juda katta guldasta, och pushti o‘ramda. Aniq tarkib do‘kon bilan tasdiqlanadi.', price: 3800000, category: 'rose', image: '/images/sonya-shom-shafaqi.webp', stock: 2, audience: ['rafiqa', 'qiz'], badge: 'Atirgullar' },
];
export const shops = [madinaShop, goldShop, sonyaShop, ...demoShops];
export const products = [...madinaProducts, ...goldProducts, ...sonyaProducts, ...demoProducts];
