import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
// Local D1 only. Never create synthetic merchant accounts in the public owner workspace.
const base = 'http://127.0.0.1:8787';
const secret = JSON.parse(readFileSync(new URL('../.cloudflare-secrets.json', import.meta.url), 'utf8')).ADMIN_TOKEN;
const id = `test-${randomUUID().slice(0, 8)}`;
const initial = 'Worker-Temporary-Password';
const permanent = 'Worker-Personal-Password';
const call = async (path, method = 'GET', body, token) => {
  const response = await fetch(`${base}/api${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  return { status: response.status, data: await response.json() };
};
assert.equal((await call('/admin/workspace')).status, 401);
const shop = { id, name: 'Worker account test', subtitle: 'Local synthetic shop', address: 'Local test address', deliveryFee: 10000, deliveryTime: '30–60 daqiqa', color: '#edf3ee', initials: 'WT', active: false };
const created = await call('/admin/onboard', 'POST', { shop, login: id, password: initial, phone: '+998900000000', telegramChatId: '123456789' }, secret);
assert.equal(created.status, 201, JSON.stringify(created.data));
const duplicate = await call('/admin/onboard', 'POST', { shop: { ...shop, id: `${id}-dup` }, login: id, password: initial, phone: '+998900000000' }, secret);
assert.equal(duplicate.status, 409);
assert.ok(!(await call('/admin/workspace', 'GET', undefined, secret)).data.some(s => s.id === `${id}-dup`));
const auth = await call('/auth/login', 'POST', { login: id, password: initial });
assert.equal(auth.status, 200, JSON.stringify(auth.data?.error));
assert.equal(auth.data.user.mustChangePassword, true);
assert.equal((await call(`/merchant/${id}/workspace`, 'GET', undefined, auth.data.token)).status, 401);
assert.equal((await call('/auth/password', 'POST', { currentPassword: initial, newPassword: permanent }, auth.data.token)).status, 200);
assert.equal((await call(`/merchant/${id}/workspace`, 'GET', undefined, auth.data.token)).status, 200);
assert.equal((await call('/merchant/lola/workspace', 'GET', undefined, auth.data.token)).status, 401);
assert.equal((await call('/admin/workspace', 'GET', undefined, auth.data.token)).status, 401);
const picture = readFileSync(new URL('../public/images/pink-bouquet.jpg', import.meta.url));
const imageUpload = await fetch(`${base}/api/merchant/${id}/images`, { method: 'POST', headers: { 'Content-Type': 'image/jpeg', Authorization: `Bearer ${auth.data.token}` }, body: picture });
assert.equal(imageUpload.status, 201, await imageUpload.clone().text());
const { url } = await imageUpload.json();
const stored = await fetch(base + url);
assert.equal(stored.status, 200);
assert.equal(stored.headers.get('content-type'), 'image/jpeg');
assert.deepEqual(Buffer.from(await stored.arrayBuffer()), picture);
const forgedImage = await fetch(`${base}/api/merchant/${id}/images`, { method: 'POST', headers: { 'Content-Type': 'image/jpeg', Authorization: `Bearer ${auth.data.token}` }, body: '<svg onload="alert(1)"></svg>' });
assert.equal(forgedImage.status, 400);
assert.equal((await call(`/admin/shops/${id}/account`, 'PATCH', { password: 'Worker-Reset-Password' }, secret)).status, 200);
assert.equal((await call('/auth/me', 'GET', undefined, auth.data.token)).status, 401);
assert.equal((await call('/auth/login', 'POST', { login: id, password: permanent })).status, 401);
assert.equal((await call(`/admin/shops/${id}/account`, 'PATCH', { enabled: false }, secret)).status, 200);
assert.equal((await call('/auth/login', 'POST', { login: id, password: 'Worker-Reset-Password' })).status, 401);
console.log('Local D1 passed: account isolation, gallery upload with exact byte roundtrip, unsafe image rejection, password change and revocation.');
