import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { chromium, expect } from '@playwright/test';
const base = process.argv[2] || 'https://gulbar.bella-rose.workers.dev';
const secrets = JSON.parse(readFileSync(new URL('../.cloudflare-secrets.json', import.meta.url), 'utf8'));
const health = await (await fetch(`${base}/api/health`)).json();
assert.equal(health.ok, true); assert.equal(health.demo, false);
const catalog = await (await fetch(`${base}/api/catalog`)).json();
assert.equal(catalog.demo, false);
assert.ok(!catalog.shops.some(s => ['lola', 'bloom', 'rayhon'].includes(s.id)));
assert.ok(!catalog.products.some(p => /^p[1-6]$/.test(p.id)));
const unsigned = await fetch(`${base}/api/orders`, { headers: { 'X-Demo-User': 'old-demo-user-123456789' } });
assert.equal(unsigned.status, 401);
assert.equal((await fetch(`${base}/api/admin/workspace`)).status, 401);
const admin = await fetch(`${base}/api/admin/workspace`, { headers: { Authorization: `Bearer ${secrets.ADMIN_TOKEN}` } });
assert.equal(admin.status, 200);
const shops = await admin.json();
assert.ok(!shops.some(s => ['lola', 'bloom', 'rayhon'].includes(s.id)));
const webhook = await fetch(`${base}/api/telegram/webhook`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Telegram-Bot-Api-Secret-Token': secrets.TELEGRAM_WEBHOOK_SECRET }, body: '{}' });
assert.equal(webhook.status, 200);
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(base);
  await page.getByRole('heading', { level: 1, name: 'Urganch guldastalari' }).waitFor();
  assert.equal(await page.locator('.app-shell.home-view').count(), 1);
  assert.equal(await page.locator('.demo-bar,.demo-note').count(), 0);
  assert.equal(await page.locator('.gm-item').count(), catalog.products.length);
  if (!catalog.products.length) await page.getByText('Hozircha gullar qo‘shilmagan.').waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'test-results/gulbar-live-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/gulbar-live-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${base}/admin`);
  assert.equal(await page.locator('.home-view.panel-view').count(), 1);
  assert.equal(await page.locator('.gm-home').count(), 0);
  await page.getByRole('heading', { name: 'Admin paneli', exact: true }).waitFor();
  assert.equal(await page.locator('.demo-note').count(), 0);
  await page.getByRole('button', { name: 'Kirish', exact: true }).waitFor();
  await page.goto(`${base}/merchant`);
  assert.equal(await page.locator('.home-view.panel-view').count(), 1);
  await page.getByRole('heading', { name: 'Do‘kon hisobiga kirish' }).waitFor();
  assert.equal(await page.locator('.demo-note').count(), 0);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ liveVerified: true, realShops: shops.length, listedShops: catalog.shops.length, products: catalog.products.length, sampleRows: 0, unsignedOrdersRejected: true, adminProtected: true, webhookReady: true }));
} finally { await browser.close(); }
