import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { ErrorBoundary } from './components/ErrorBoundary';
import './styles.css';
import './home.css';
import './home-feed.css';
import './home-wheel.css';
import './home-minimal.css';
import './home-tools.css';
import './panel.css';
import './extras.css';
import './checkout-v2.css';
import './payments.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ErrorBoundary><App /></ErrorBoundary></React.StrictMode>);
